train_PA:
  gpu: 1 # device
  batch_size: 1
  epoch: 30
  lr: 0.00002
  weight_decay: 0.01

  pretrained: null
  scheduler_step_size: 1

train_CT:
  gpu: 1 # device
  batch_size: 1
  epoch: 30
  lr: 0.00003
  weight_decay: 0.0001

  pretrained: null
  scheduler_step_size: 1

model:
  name: resnet50 # resnet18, resnet50

data:
  random_state: 42
  data_version: v0 # dataset version
  CT_dim: [512, 512]
  PA_dim: [2048, 1024]
  data_generation: true # set true if you want to generate data, set false when training
  modal: panorama # data_generation modal: CT, panorama
  dir: axial # axial, coronal(, sagittal)

  # split_label
  split_modal: panorama # CT, panorama

  # data_dir: /home/user/onj/dataset/${data.data_version}
  data_dir: /mnt/aix22301/onj/dataset/${data.data_version}
  ONJ_dir: ${data.data_dir}/ONJ_labeling
  NON_ONJ_dir: ${data.data_dir}/Non_ONJ_soi
  label_dir: /mnt/aix22301/onj/dataset/${data.data_version}/label_v231122/label.json

  split_ratio: 0.8
  test_split: true