mode: train # train, predict, cam

train_PA:
  # gpu: 1 # device
  batch_size: 4
  epoch: 100
  lr: 0.00001
  weight_decay: 0.0001

  pretrained: null
  scheduler_step_size: 1

train:
  # commented out for manual device selection
  # example: python3 code/scripts/train.py train.gpu=1
  # gpu: 1 
  # description: "null"
  batch_size: 1
  accumulation_step: 1 # should set to divisor of 16 (16의 약수로 설정할 것) (why? log_step=16)
  epoch: 50
  lr: 0.00001
  weight_decay: 0.0001

  # pretrained_CT: /mnt/aix22301/onj/checkpoints/CT_backbone/ResNet50/resnet50_best_less_overfitting.pth
  pretrained_CT: /mnt/aix22301/onj/checkpoints/CT_backbone/ResNet50/resnet50_best.pth
  # pretrained_CT: ""
  pretrained_YOLO: /mnt/aix22301/onj/outputs/2024-05-06/15-20-18/runs/detect/train/weights/last.pt # doesn't affect PA model 
  pretrained_PA: /mnt/aix22301/onj/checkpoints/PA_backbone/YOLO/backbone_PA_best_model.pth
  # pretrained_PA: ""
  
  # pretrained_fusion: /mnt/aix22301/onj/checkpoints/Fusion/Concat/concat_resnet50_yolo_best.pth
  pretrained_fusion: ""
  scheduler_step_size: 1

model:
  CT: resnet50 # resnet18, resnet50
  PA: yolo # no other options (240516)
  fusion: concat # concat, (TODO: attention, mamba)
  freeze_2d: false # freeze PA backbone
  freeze_3d: false # freeze CT backbone

  # expand PA feature vector size to match CT feature vector size
  low_channels: 64
  low_expanded: 512

  mid_channels: 128
  mid_expanded: 1024

  high_channels: 256
  high_expanded: 2048


data:
  random_state: 42
  data_version: v2 # dataset version
  CT_dim: [512, 512]
  PA_dim: [2048, 1024]
  data_generation: true # set true if you want to generate data, set false when training
  modal: panorama # data_generation modal: CT, panorama
  dir: axial # axial, coronal(, sagittal)

  # split_label
  split_modal: CT # CT, panorama

  # data_dir: /home/user/onj/dataset/${data.data_version}
  data_dir: /mnt/aix22301/onj/dataset/${data.data_version}
  # ONJ_dir: ${data.data_dir}/ONJ_labeling
  # NON_ONJ_dir: ${data.data_dir}/Non_ONJ_soi
  ONJ_dir: ${data.data_dir}/onj
  NON_ONJ_dir: ${data.data_dir}/non_onj
  label_dir: /mnt/aix22301/onj/dataset/${data.data_version}/label_20241007.json

  split_ratio: 0.8
  test_split: true